### ISSUE TITLE
Witnesses errors out with some strange error in "Getting Started" guide

### ISSUE THREAD

**Issue by daidoji** [hyperledger-labs/did-webs-resolver#68]
Got to this section: https://github.com/hyperledger-labs/did-webs-resolver/blob/main/GETTING_STARTED.md#optional-example-in-docker-using-witnesses

Ran the  ./get_started_docker_wits.sh script and got the following error on the second step.  (Had done rest of the Getting Started guide above).  Output listed below.

```
webs:/usr/local/var/webs/volume/dkr/examples# ./get_started_docker_wits.sh
KERI Keystore created at: /usr/local/var/keri/ks/controller                                                                                                                                 KERI Database created at: /usr/local/var/keri/db/controller                                                                                                                                 KERI Credential Store created at: /usr/local/var/keri/reg/controller                                                                                                                        
Loading 3 OOBIs...
http://witnesshost:5642/oobi/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha/controller succeeded
http://witnesshost:5643/oobi/BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM/controller succeeded
http://witnesshost:5644/oobi/BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX/controller succeeded
https://weboftrust.github.io/oobi/EN6Oh5XSD5_q2Hgu-aqpdfbVepdpYpFlgz6zvJL5b_r5 succeeded
http://witnesshost:5642/oobi/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha/controller resolved
http://witnesshost:5643/oobi/BLskRTInXnMxWaGqcpSyMgo0nYbalW99cGZESrz3zapM/controller resolved
http://witnesshost:5644/oobi/BIKKuvBwpmDVA4Ds-EpL5bt9OqPzWPja2LigFYZN2YfX/controller resolved
ERR: Already incepted pre=DHr0-I-mMN7h6cLMOTRJkkfPuMd0vgQPrOk4Y3edaHjr.

Press enter to generate did:webs...
Generate DID document command did:webs:did-webs-service%3a7676:EKYGGh-FtAphGmSZbsuBs_t4qpsjYJ2ZqvMKluq9OxmP using oobi None and metadata False registry name for creds None
Generating CESR event stream data from hab
Generating EKYGGh-FtAphGmSZbsuBs_t4qpsjYJ2ZqvMKluq9OxmP KEL CESR events
Writing CESR events to EKYGGh-FtAphGmSZbsuBs_t4qpsjYJ2ZqvMKluq9OxmP/keri.cesr:

Generating DID document for did:webs:did-webs-service%3a7676:EKYGGh-FtAphGmSZbsuBs_t4qpsjYJ2ZqvMKluq9OxmP with aid EKYGGh-FtAphGmSZbsuBs_t4qpsjYJ2ZqvMKluq9OxmP using oobi None and metadata False registry name for creds None
Habery does not have a kever for did:webs:did-webs-service%3a7676:EKYGGh-FtAphGmSZbsuBs_t4qpsjYJ2ZqvMKluq9OxmP. Did you parse the keri.cesr file?
Known kevers:  ENro7uf0ePmiK3jdTo2YCdXLqW7z7xoP6qhhBou6gBLe
Traceback (most recent call last):
  File "/keripy/venv/bin/dkr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/var/webs/src/dkr/app/cli/dkr.py", line 33, in main
    raise ex
  File "/usr/local/var/webs/src/dkr/app/cli/dkr.py", line 30, in main
    directing.runController(doers=doers, expire=0.0)
  File "/keripy/venv/lib/python3.12/site-packages/keri/app/directing.py", line 665, in runController
    doist.do(doers=doers)
  File "/keripy/venv/lib/python3.12/site-packages/hio/base/doing.py", line 156, in do
    self.recur()  # increments .tyme runs recur context
    ^^^^^^^^^^^^
  File "/keripy/venv/lib/python3.12/site-packages/hio/base/doing.py", line 275, in recur
    tock = dog.send(self.tyme)  # yielded tock == 0.0 means re-run asap
           ^^^^^^^^^^^^^^^^^^^
  File "/keripy/venv/lib/python3.12/site-packages/hio/base/doing.py", line 922, in do
    self.done = self.recur(tyme=tyme)  # equv of doist.recur
                ^^^^^^^^^^^^^^^^^^^^^
  File "/keripy/venv/lib/python3.12/site-packages/hio/base/doing.py", line 1026, in recur
    tock = dog.send(tyme)  # yielded tock == 0.0 means re-run asap
           ^^^^^^^^^^^^^^
  File "/usr/local/var/webs/src/dkr/app/cli/commands/did/webs/generate.py", line 111, in generate
    result = didding.generateDIDDoc(self.hby, did=self.did, aid=aid, oobi=None, reg_name=self.da_reg, meta=self.meta)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/var/webs/src/dkr/core/didding.py", line 86, in generateDIDDoc
    hby.kevers[aid]
    ~~~~~~~~~~^^^^^
  File "/keripy/venv/lib/python3.12/site-packages/keri/db/basing.py", line 68, in __getitem__
    raise ex  # reraise KeyError
    ^^^^^^^^
  File "/keripy/venv/lib/python3.12/site-packages/keri/db/basing.py", line 63, in __getitem__
    return super(dbdict, self).__getitem__(k)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'EKYGGh-FtAphGmSZbsuBs_t4qpsjYJ2ZqvMKluq9OxmP'
```

Looks like this script is meant to be run _instead_ of the GETTING_STARTED.md steps or the `getting_started_docker.sh` script so we should adjust the guide to reflect this to prevent confusion.

**Comment by 2byrds** [comment]
This could be a refactor but we have added a note for now
